Import( 'env' )
Import( 'compmap' )
import profiles

profiles.make_rpal_master( env )
profiles.Program(
        'libOs_test',
        profiles.RpalModule()
        ).Target( env, 'main.c', compmap, 'cunit', 'rpal', 'Os', 'rpcm' )

# EOF
