Import( 'env' )
Import( 'compmap' )
import profiles

profiles.make_rpal_master( env )
profiles.Program(
        'rpcm_test',
        profiles.RpalModule()
        ).Target( env, 'main.c', compmap, 'cunit', 'rpal', 'rpcm', 'cryptoLib' )

# EOF
