Import( 'env' )
Import( 'compmap' )
import profiles

profiles.DynamicLibrary(
        'rpHCP_KernelAcquisition',
        profiles.ObfuscatedHeader(),
        profiles.GitInfo(),
        LIBS = 'm'
        ).Target(
            env,
            Glob( '*.c' ),
            compmap,
            'rpHostCommonPlatformIFaceLib',
            'cryptoLib',
            'Os',
            'obfuscationLib',
            )


# EOF
